name: Blind review collect job

on:
  schedule:
    - cron: '0 0 0 0 0'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Launch job
      env:
        ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
        ES_BASE64_AUTH: ${{ secrets.ES_BASE64_AUTH }}
      run: |
        python -m blindreviewparser \
            --es-endpoint="${ES_ENDPOINT}" \
            --es-base64-auth="${ES_BASE64_AUTH}" \
            --p-num-start=1 \
            --p-num-end=100
